import { Fragment, useEffect, useState, type ReactNode } from 'react';
import { motion, MotionConfig, type Transition } from 'framer-motion';
import { ArrowLeft, ArrowRight, Check, ChevronDown, Menu, Monitor, Pause, Play, Smartphone, X } from 'lucide-react';

const gravityBounce: Transition = { type: 'spring', stiffness: 110, damping: 11, mass: 1 };

const CALL_URL='https://www.experienceplus.ai/book';
const RETAINER_URL='https://buy.stripe.com/5kQaEZfeh0tqf3k7Q4bo400';
const navLinks:[string,string][]=[['Work','#work'],['Services','#services'],['Process','#process'],['Sample','#sample'],['Packages','#packages'],['About','#about']];
const packages=[
  {name:'Foundation',label:'Find your position',price:'From $2,400',items:['Positioning workshop','Messaging foundation','Visual direction','Profile image set','LinkedIn + biography refresh']},
  {name:'Signature',label:'Build the full system',price:'From $6,800',featured:true,items:['Everything in Foundation','Editorial photo direction','Personal brand film','30-day social launch library','Website hero system']},
  {name:'Ongoing',label:'Stay recognizable',price:'Custom monthly',items:['Quarterly creative direction','Monthly image + video production','Campaign concepts','Social content system','Performance review']},
];
const services=[['01','Position','A clear point of view, audience, promise, and voice before a camera turns on.'],['02','Direct','A visual world built around your presence—not borrowed from somebody else’s feed.'],['03','Produce','Portraits, brand films, vertical video, and campaign assets from one direction.'],['04','Launch','A reusable system for LinkedIn, Instagram, press, speaking, and your own site.']];
const audiences=['Founders & executives','Consultants & advisors','Creators & speakers','Independent professionals','Hospitality & wellness','Career reinvention'];
type Duo=[string,string];
type Client={name:string;role:string;portrait:string;film:string;brief:string;before:Duo[];after:Duo[];sheet:Duo[];statement:string;lede:string;long:string;audience:[string,string[]][];voice:Duo[];pillars:Duo[];palette:Duo[];direction:[string,string[]][];use:Duo[];tiles:[string,string,string,string];week:string[];site:{domain:string;nav:string[];kicker:string;h:string;p:string;projects:Duo[];aboutH:string;aboutP:string;aboutImg:string;journal:Duo[];foot:string}};
const CLIENTS:Client[]=[
  {name:"Astrid Berg",role:"Architect · Copenhagen",portrait:"portrait-architect",film:"astrid-film",
   brief:"\u201cI'm an architect in Copenhagen\u2014fifteen years, mostly housing. The work is good, but online I basically don't exist. These photos are all I have. Can you help?\u201d",
   before:[["before-snap-1","IMG_2041.jpg"],["before-snap-2","IMG_2318.jpg"]],
   after:[["portrait-architect","Brand book"],["project-koge","Website"],["headshot-press","Headshots"],["astrid-film","Brand film"]],
   sheet:[["portrait-architect","Profile \u2014 the original session"],["headshot-press","Press \u2014 studio"],["headshot-speaker","Speaker \u2014 stage"],["headshot-editorial","Editorial \u2014 on site"]],
   statement:"Housing that lowers the temperature of city life\u2014for development partners who want density without noise.",
   lede:"Astrid Berg designs housing that lowers the temperature of city life\u2014Nordic material honesty, hard density numbers, and approvals the neighbors don't fight.",
   long:"Most cities argue about density in decibels. Astrid's buildings answer quietly: courtyards that hold the afternoon, limewash that ages instead of dating, unit counts that pencil without a single rendering trick. Fifteen years of practice proving that calm is not the opposite of density\u2014it is how density gets approved.",
   audience:[["Built for",["Development partners with long horizons","Planners who count daylight, not just units","Journalists covering livable density","Juries, panels, and speaking programs"]],["Not for",["Trophy-tower briefs","Render-first developers","Anyone shopping for spectacle"]]],
   voice:[["Warm","A host, not a lecturer. First names, short sentences, materials before metrics."],["Precise","Numbers only where they carry weight\u2014spans, budgets, daylight hours."],["Unhurried","No urgency theater. A long idea is allowed to take a paragraph."]],
   pillars:[["Density without noise","Why calm scales. The economics of approvals. The neighbor test."],["Material honesty","Limewash, oak, and budgets\u2014what ages well and what only photographs well."],["The hour after work","Homes at rest. Daylight as a spec. The quiet job of housing."]],
   palette:[["Limewash","#E7E1D5"],["Oak","#C8A57B"],["Graphite","#2E3236"],["Nordic sky","#B9C6CE"]],
   direction:[["Always",["Natural light, working context","Materials and models in frame","Eye level, mid-distance","Weather allowed"]],["Never",["Arms-crossed LinkedIn pose","Hard studio flash","Skyline hero shots","Renders passed off as photos"]]],
   use:[["LinkedIn headline","Architect for housing that lowers the temperature of city life."],["Speaker introduction","Astrid designs calm\u2014dense housing that trades spectacle for warmth, and wins approvals because the neighbors want to live next to it."],["Biography, first line","I build for the hour after work, when a home has to do its quiet job."]],
   tiles:["Calm is a density strategy.","31 units.","Zero neighbor objections.","project-koge"],
   week:["Mon \u2014 Position quote card","Wed \u2014 Project: K\u00f8ge Courtyards, four frames","Fri \u2014 Essay: The neighbor test"],
   site:{domain:"astridberg.dk",nav:["Work","Journal","Contact"],kicker:"Architect · Copenhagen",h:"Calm is a density strategy.",p:"Housing for the hour after work\u2014dense, warm, and approved without a fight.",projects:[["K\u00f8ge Courtyards","project-koge"],["Limewash Row","project-limewash"],["Harbor Commons","project-harbor"]],aboutH:"Fifteen years of quiet buildings.",aboutP:"Astrid's practice pairs Nordic material honesty with hard density numbers. The work begins with the neighbors, not the skyline\u2014and it gets approved because of it.",aboutImg:"headshot-editorial",journal:[["Mar 2026","The neighbor test"],["Jan 2026","Limewash, ten years on"],["Nov 2025","Density at speaking voice"]],foot:"studio@astridberg.dk · Copenhagen"}},
  {name:"Amara Osei",role:"Founder · London",portrait:"portrait-founder",film:"amara-film",
   brief:"\u201cI run a software company in London\u2014twelve years in. The product is solid but my presence is nonexistent, and investors google me. These are the only photos I have. Help?\u201d",
   before:[["f-before-1","IMG_0873.jpg"],["f-before-2","IMG_1149.jpg"]],
   after:[["portrait-founder","Brand book"],["f-project-1","Website"],["f-headshot-press","Headshots"],["amara-film","Brand film"]],
   sheet:[["portrait-founder","Profile \u2014 the original session"],["f-headshot-press","Press \u2014 studio"],["f-headshot-speaker","Speaker \u2014 stage"],["f-headshot-editorial","Editorial \u2014 the gallery office"]],
   statement:"Technology people can trust\u2014shipped weekly, explained like a human, signed by its founder.",
   lede:"Amara Osei builds technology people can trust\u2014shipped weekly, explained plainly, led in the open.",
   long:"Most tech companies narrate themselves in acronyms. Amara's ships speak instead: weekly releases, plain release notes, a founder who signs her work and answers for it. Twelve years from engineer to founder taught her the quiet rule of the industry\u2014trust is not a feature you add later.",
   audience:[["Built for",["Enterprise partners and buyers","Journalists covering technology with care","Conference and podcast programs","Senior hires deciding where to work"]],["Not for",["Hype cycles and vaporware","Growth-at-any-cost theater","Buzzword panels"]]],
   voice:[["Plain","Release-note English. If a customer can't repeat it, it isn't said."],["Confident","Statements, not hedges. Numbers carry the weight."],["Accountable","Signs her work. Mistakes get named, dated, and fixed in public."]],
   pillars:[["Ship in the open","Weekly releases, plain notes, visible roadmaps."],["Explain like a human","No acronym where a sentence will do."],["Trust is the product","Reliability, privacy, and the receipts to prove both."]],
   palette:[["Gallery white","#F2F2EF"],["Cobalt","#1F41BB"],["Ink","#16181D"],["Silk","#EDE6DA"]],
   direction:[["Always",["Daylight offices and galleries","In motion, mid-thought","One cobalt accent in frame","Real rooms, real work"]],["Never",["Hoodie-at-a-laptop clich\u00e9s","Neon tech gradients","Stock handshake optics","Crossed arms in a server room"]]],
   use:[["LinkedIn headline","Founder building technology people can trust\u2014shipped weekly, explained plainly."],["Speaker introduction","Amara Osei ships trust: software released weekly, explained in plain English, and signed by the founder who answers for it."],["Biography, first line","I build software the way I'd want it explained to me."]],
   tiles:["Trust ships weekly.","52 releases.","Zero jargon.","f-project-1"],
   week:["Mon \u2014 Position quote card","Wed \u2014 Release notes, annotated","Fri \u2014 Essay: Plain English is a feature"],
   site:{domain:"amaraosei.com",nav:["Work","Writing","Contact"],kicker:"Founder · London",h:"Trust ships weekly.",p:"Technology explained like a human\u2014built by a team proud to sign its work.",projects:[["Halcyon Pay","f-project-1"],["Studio North","f-project-2"],["Foundry Sessions","f-project-3"]],aboutH:"Twelve years of shipping in the open.",aboutP:"Amara pairs engineering discipline with plain language. The work leads with receipts\u2014releases, notes, and numbers\u2014so the story never has to stretch.",aboutImg:"f-headshot-editorial",journal:[["Apr 2026","Plain English is a feature"],["Feb 2026","What weekly shipping taught me"],["Dec 2025","Signing your work"]],foot:"hello@amaraosei.com · London"}},
  {name:"Mateo Ferrer",role:"Chef · Barcelona",portrait:"portrait-chef",film:"mateo-film",
   brief:"\u201cI own three restaurants in Barcelona. Guides write about us, but every photo of me is from a phone at the pass. I need to look like the rooms feel. Can you help?\u201d",
   before:[["c-before-1","IMG_5512.jpg"],["c-before-2","IMG_5544.jpg"]],
   after:[["portrait-chef","Brand book"],["c-project-1","Website"],["c-headshot-press","Headshots"],["mateo-film","Brand film"]],
   sheet:[["portrait-chef","Profile \u2014 the original session"],["c-headshot-press","Press \u2014 studio"],["c-headshot-speaker","Speaker \u2014 chef's table"],["c-headshot-editorial","Editorial \u2014 the market"]],
   statement:"Provenance you can taste\u2014three rooms built on craft, seasons, and patience.",
   lede:"Mateo Ferrer cooks provenance: three rooms in Barcelona built on craft, seasons, and fourteen producers he calls by name.",
   long:"Most restaurant brands sell spectacle. Mateo's rooms sell certainty: the farm on the plate, the season in the menu, a fire that has burned since opening night. Twenty years from line cook to owner taught him that a restaurant is a promise kept nightly\u2014and the brand is simply that promise, written down.",
   audience:[["Built for",["Producers and farmers he partners with","Food writers and guides","Destination guests who book ahead","Hospitality investors with patience"]],["Not for",["Franchise offers","TV spectacle","Trend menus"]]],
   voice:[["Warm","Speaks like a host at the pass\u2014first names, short invitations."],["Rooted","Every claim traces to a farm, a season, a fire."],["Exacting","Details are the argument: grams, hours, embers."]],
   pillars:[["Provenance first","Fourteen producers, named and visited."],["The room is the recipe","Light, ceramic, and fire as part of the dish."],["Craft over spectacle","No foam theater\u2014technique in service of taste."]],
   palette:[["Linen","#E8E0D2"],["Char","#2A2724"],["Ember","#B4552D"],["Olive","#6A6B4A"]],
   direction:[["Always",["Fire, steam, and working hands","Morning markets and producers","Warm tungsten and candlelight","The pass, mid-service"]],["Never",["White-tablecloth stiffness","Overhead flat-lays","Tweezers-as-theater close-ups","Stock crossed-arms chef pose"]]],
   use:[["LinkedIn headline","Chef-owner of three Barcelona rooms built on provenance, craft, and patience."],["Speaker introduction","Mateo Ferrer cooks certainty\u2014three rooms where the farm is on the plate and the fire never went out."],["Biography, first line","I cook what the season writes, and I name the people who grew it."]],
   tiles:["The room is the recipe.","3 rooms.","Fourteen producers, named.","c-project-2"],
   week:["Mon \u2014 Position quote card","Wed \u2014 Producer visit: four frames","Fri \u2014 Essay: The fire at Brasa"],
   site:{domain:"mateoferrer.es",nav:["Restaurants","Journal","Contact"],kicker:"Chef · Barcelona",h:"Provenance you can taste.",p:"Three rooms, one idea: craft over spectacle, seasons over trends.",projects:[["Brasa","c-project-1"],["Comal","c-project-2"],["Sal","c-project-3"]],aboutH:"Twenty years, one fire.",aboutP:"Mateo pairs market mornings with exacting service. The brand work names what was already true: the producers, the seasons, the room built around the fire.",aboutImg:"c-headshot-editorial",journal:[["Apr 2026","The fire at Brasa"],["Jan 2026","Fourteen producers"],["Oct 2025","What the season writes"]],foot:"hola@mateoferrer.es · Barcelona"}},
];
const delivCaps=['An excerpt\u2014the full Foundation book runs about 28 pages.','Website hero system\u2014included in Signature.','Profile image set\u2014an AI-directed set grown from one reference session. Included in Foundation.','Personal brand film\u2014included in Signature. An AI-directed sample cut for the fictional client.'];
function bookPagesFor(c:Client){return [
  {k:'Position',tag:'Foundation',el:<p className="book-statement">{c.statement}</p>},
  {k:'Story',tag:'Foundation',el:<div><p className="lede">{c.lede}</p><p className="bio-long"><b>Long bio, first paragraph — </b>{c.long}</p></div>},
  {k:'Audience',tag:'Foundation',el:<div className="for-grid">{c.audience.map(([h,xs])=><div key={h}><h5>{h}</h5><ul>{xs.map(x=><li key={x}>{x}</li>)}</ul></div>)}</div>},
  {k:'Voice',tag:'Foundation',el:<div className="voice-grid">{c.voice.map(([t,d])=><div key={t}><strong>{t}</strong><p>{d}</p></div>)}</div>},
  {k:'Pillars',tag:'Foundation',el:<div className="pillar-list">{c.pillars.map(([t,d])=><div key={t}><strong>{t}</strong><p>{d}</p></div>)}</div>},
  {k:'Type',tag:'Foundation',el:<div className="type-spec"><div className="serif"><b>Aa</b><p><strong>Display — IBM Plex Serif.</strong> Headlines at speaking voice: sentence case, no exclamation marks.</p></div><div><b>Aa</b><p><strong>Text — DM Sans.</strong> Short lines, generous leading, numbers set small and exact.</p></div></div>},
  {k:'Palette',tag:'Foundation',el:<div className="swatch-row">{c.palette.map(([n,cc])=><div className="swatch" key={n}><i style={{background:cc}}/><span>{n}</span><small>{cc}</small></div>)}</div>},
  {k:'Image direction',tag:'Foundation',el:<div className="for-grid">{c.direction.map(([h,xs])=><div key={h}><h5>{h}</h5><ul>{xs.map(x=><li key={x}>{x}</li>)}</ul></div>)}</div>},
  {k:'In use',tag:'Foundation',el:<div className="use-list">{c.use.map(([w,t])=><div key={w}><span>{w}</span><p>{t}</p></div>)}</div>},
  {k:'Social launch',tag:'Signature',el:<div><div className="tile-row"><div className="tile quote">“{c.tiles[0]}”</div><div className="tile stat"><b>{c.tiles[1]}</b><span>{c.tiles[2]}</span></div><div className="tile img"><img src={`/images/${c.tiles[3]}.webp`} alt="Sample social image tile"/></div></div><div className="week-strip">{c.week.map(w=><span key={w}>{w}</span>)}</div></div>},
];}

function Mark(){return <svg className="mark" viewBox="0 0 32 32" aria-hidden="true"><circle cx="16" cy="16" r="14.4" fill="none" stroke="currentColor" strokeWidth="1.6"/><circle cx="13.2" cy="13.8" r="1.25" fill="currentColor"/><circle cx="18.6" cy="12.6" r="1.25" fill="currentColor"/><circle cx="19.2" cy="18.2" r="1.25" fill="currentColor"/><circle cx="14" cy="19.4" r="1.25" fill="currentColor"/><circle cx="16.5" cy="15.9" r="1.25" fill="currentColor"/></svg>}
function Logo(){return <><Mark/><span className="lt"><span>Lilikoi</span><small>Personal branding studio</small></span></>}
function Reveal({children,className=''}:{children:ReactNode;className?:string}){return <motion.div className={`reveal ${className}`} initial={{y:-44,opacity:0}} whileInView={{y:0,opacity:1}} viewport={{once:true,amount:0.15}} transition={gravityBounce}>{children}</motion.div>}
function Words({text}:{text:string}){let i=0;return <>{text.split('\n').map((line,li)=><Fragment key={li}>{li>0&&<br/>}{line.split(' ').map((w,wi)=><Fragment key={wi}>{wi>0&&' '}<motion.span style={{display:'inline-block',willChange:'transform'}} initial={{y:'-0.8em',opacity:0}} whileInView={{y:0,opacity:1}} viewport={{once:true,amount:0.5}} transition={{...gravityBounce,delay:i++*0.07}}>{w}</motion.span></Fragment>)}</Fragment>)}</>}
function Video({name,className='',loop=true}:{name:string;className?:string;loop?:boolean}){const [paused,setPaused]=useState(false);return <div className={`video-wrap ${className}`}><video autoPlay={!paused} muted loop={loop} playsInline preload="metadata" poster={`/images/${name}.webp`} ref={el=>{if(el)paused?el.pause():!el.ended&&el.play().catch(()=>{})}}><source src={`/media/${name}.mp4`} type="video/mp4"/></video><button className="video-control" onClick={()=>setPaused(!paused)} aria-label={paused?'Play background video':'Pause background video'}>{paused?<Play/>:<Pause/>}</button></div>}
function HeroCycle({names}:{names:string[]}){const [idx,setIdx]=useState(0);const [paused,setPaused]=useState(false);return <div className="video-wrap">{names.map((n,i)=>{const active=i===idx;const nxt=i===(idx+1)%names.length;return <video key={n} className={active?'hero-clip on':'hero-clip'} muted playsInline preload={active||nxt?'auto':'none'} poster={`/images/${n}.webp`} ref={el=>{if(!el)return;if(active&&!paused){el.play().catch(()=>{})}else{el.pause();if(!active)el.currentTime=0}}} onEnded={()=>{if(active)setIdx((idx+1)%names.length)}}><source src={`/media/${n}.mp4`} type="video/mp4"/></video>})}<button className="video-control" onClick={()=>setPaused(!paused)} aria-label={paused?'Play background video':'Pause background video'}>{paused?<Play/>:<Pause/>}</button></div>}
function Still({name,alt}:{name:string;alt:string}){return <div className="video-wrap"><img src={`/images/${name}.webp`} alt={alt} loading="lazy"/></div>}
function Checkout({choice,onClose}:{choice:string;onClose:()=>void}){useEffect(()=>{document.body.style.overflow='hidden';const k=(e:KeyboardEvent)=>e.key==='Escape'&&onClose();addEventListener('keydown',k);return()=>{document.body.style.overflow='';removeEventListener('keydown',k)}},[onClose]);return <div className="modal-bg" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="checkout" role="dialog" aria-modal="true" aria-labelledby="checkout-title"><button className="modal-x" onClick={onClose} aria-label="Close"><X/></button><p className="kicker">Secure retainer</p><h2 id="checkout-title">{choice}</h2><p>Reserve your project with a $500 retainer. Final scope, schedule, and total pricing are confirmed separately in a written proposal.</p><div className="stripe-stub"><span>Stripe Checkout</span><strong>$500 project retainer</strong><small>Secure payment opens in a new tab.</small></div><a className="btn dark" href={RETAINER_URL} target="_blank" rel="noreferrer">Pay $500 retainer <ArrowRight/></a><small>Payment is securely processed by Stripe.</small></div></div>}

export default function App(){const [menu,setMenu]=useState(false);const [checkout,setCheckout]=useState<string|null>(null);const [deliv,setDeliv]=useState(0);const [page,setPage]=useState(0);const [siteMobile,setSiteMobile]=useState(false);const [scrolled,setScrolled]=useState(false);const [ci,setCi]=useState(0);
  useEffect(()=>{const f=()=>setScrolled(window.scrollY>24);f();addEventListener('scroll',f,{passive:true});return()=>removeEventListener('scroll',f)},[]);
  const c=CLIENTS[ci];const pages=bookPagesFor(c);const first=c.name.split(' ')[0];
  return <MotionConfig reducedMotion="user">
  <header className={scrolled||menu?'scrolled':''}><a className="logo" href="#top"><Logo/></a><nav className={menu?'open':''}>{navLinks.map(([l,h])=><a href={h} onClick={()=>setMenu(false)} key={l}>{l}</a>)}<a className="nav-cta" href="#packages">Build your brand</a></nav><button className="menu" onClick={()=>setMenu(!menu)} aria-label="Toggle menu">{menu?<X/>:<Menu/>}</button></header>
  <main id="top">
    <section className="hero"><HeroCycle names={['hero-solo','hero-3','hero-4','hero-5','hero-2']}/><div className="hero-shade"/><Reveal className="hero-copy"><p className="kicker light">Strategy · Photography · Video · Content</p><h1><Words text={'A personal brand\npeople remember.'}/></h1><p>One recognizable system for how you look, sound, and show up—built with human direction and AI-accelerated production.</p><div className="actions"><a className="btn light" href="#packages">Build your brand <ArrowRight/></a><a className="text-btn" href="#work">See the work <ChevronDown/></a></div></Reveal></section>
    <section className="intro"><Reveal><p className="kicker">The proposition</p><h2><Words text={'Your brand should look as credible as the work behind it.'}/></h2></Reveal><Reveal className="intro-copy"><p>You already have a reputation. We turn it into a deliberate visual and verbal system—so the person people meet online matches the authority you bring into the room.</p><div className="audience-list">{audiences.map(x=><span key={x}>{x}</span>)}</div></Reveal></section>
    <section id="work" className="film-chapter"><Video name="founder-solo-2"/><div className="film-overlay"/><Reveal><p className="kicker light">Founder presence</p><h2><Words text={'Be visible.\nStay yourself.'}/></h2><p>Editorial imagery with enough polish to travel—and enough humanity to be believed.</p></Reveal></section>
    <section id="services" className="services"><Reveal className="section-head"><p className="kicker">One coherent identity</p><h2><Words text={'Strategy before content.\nA system before a feed.'}/></h2></Reveal><div className="service-grid">{services.map(([n,t,d])=><Reveal key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></Reveal>)}</div></section>
    <section className="portrait-work"><Reveal className="section-head"><p className="kicker">Selected directions</p><h2><Words text={'One person.\nA world built around them.'}/></h2></Reveal><div className="portrait-grid"><figure><img src="/images/portrait-architect.webp" alt="Editorial personal brand portrait of an architect in a Nordic studio" loading="lazy"/><figcaption><span>Architecture</span><strong>Quiet authority</strong></figcaption></figure><figure><img src="/images/portrait-founder.webp" alt="Editorial personal brand portrait of a technology founder in a gallery" loading="lazy"/><figcaption><span>Technology</span><strong>Visible leadership</strong></figcaption></figure><figure><img src="/images/portrait-chef.webp" alt="Editorial personal brand portrait of a chef founder" loading="lazy"/><figcaption><span>Hospitality</span><strong>Craft as identity</strong></figcaption></figure></div></section>
    <section className="split-film"><Still name="cd-still" alt="Creative director reviewing editorial photography in a studio"/><Reveal><p className="kicker">Creative direction</p><h2><Words text={'AI makes production faster. Taste makes it yours.'}/></h2><p>We use AI to expand the shot list, explore campaigns, and multiply formats. Every choice still passes through a human point of view.</p><ul><li><Check/>Environmental and studio portraits</li><li><Check/>Short-form and campaign video</li><li><Check/>Typography-led social assets</li><li><Check/>Website, press, and speaker kits</li></ul></Reveal></section>
    <section id="process" className="process"><Reveal><p className="kicker light">The process</p><h2><Words text={'From point of view\nto public presence.'}/></h2></Reveal><div className="process-line">{['Discover','Position','Direct','Produce','Launch','Evolve'].map((x,i)=><Reveal key={x}><b>{String(i+1).padStart(2,'0')}</b><span>{x}</span></Reveal>)}</div></section>
    <section className="film-chapter strategy"><Video name="strategy-film-v2"/><div className="film-overlay"/><Reveal><p className="kicker light">Built together</p><h2><Words text={'Your expertise.\nOur direction.'}/></h2><p>The work begins at a table, not inside a generator.</p></Reveal></section>
    <section id="sample" className="sample"><Reveal className="section-head"><p className="kicker">Sample deliverables</p><h2><Words text={'What you actually\ntake home.'}/></h2><p>Three composite clients—an architect, a founder, and a chef, all invented—each carried through the full system: brand book, website, headshot set, and film. Everything below is sample work; the clients, their projects, and the quotes are fictional.</p></Reveal>
    <Reveal><div className="client-tabs" role="tablist">{CLIENTS.map((x,i)=><button key={x.name} role="tab" aria-selected={i===ci} className={i===ci?'on':''} onClick={()=>{setCi(i);setPage(0)}}><img src={`/images/${x.portrait}.webp`} alt="" loading="lazy"/><span className="ct"><b>{x.name}</b><small>{x.role}</small></span></button>)}</div></Reveal>
    <Reveal className="ba"><div className="ba-before"><div className="panel-head"><p className="kicker">What {first} sent</p><em className="demo-tag">Fictional client — demonstration only</em></div><div className="ba-snaps">{c.before.map(([img,f])=><figure key={img}><img src={`/images/${img}.webp`} alt={`Casual snapshot the fictional client uploaded (${f})`} loading="lazy"/><figcaption>{f}</figcaption></figure>)}</div><div className="ba-note"><span>brief-bio.txt</span><p>{c.brief}</p></div></div><div className="ba-arrow" aria-hidden="true"><ArrowRight/></div><div className="ba-after"><div className="panel-head"><p className="kicker">What {first} took home</p><em className="demo-tag">Sample work — demonstration only</em></div><p className="ba-hint">Choose a deliverable — it opens below.</p><div className="ba-grid" role="tablist">{c.after.map(([img,l],i)=><button key={l} role="tab" aria-selected={i===deliv} className={deliv===i?'on':''} onClick={()=>setDeliv(i)}><img src={`/images/${img}.webp`} alt="" loading="lazy"/><span className="ba-foot"><b>{l}</b><small>{deliv===i?'Viewing':'View'} <ChevronDown/></small></span></button>)}</div></div></Reveal>
    {deliv===0&&<div className="book"><div className="book-cover"><img src={`/images/${c.portrait}.webp`} alt="Cover of a sample personal brand book for a fictional client" loading="lazy"/><div className="book-id"><p className="kicker light">Brand book · Vol. 01</p><strong>{c.name}</strong><span>{c.role}</span></div></div><div className="book-pages paged"><div className="book-page"><div className="page-head"><h4>{String(page+1).padStart(2,'0')} · {pages[page].k}</h4><span className="page-tag">{pages[page].tag}</span></div>{pages[page].el}</div><div className="book-controls"><span>Page {String(page+1).padStart(2,'0')} / {String(pages.length).padStart(2,'0')}</span><div><button onClick={()=>setPage(page-1)} disabled={page===0} aria-label="Previous page"><ArrowLeft/></button><button onClick={()=>setPage(page+1)} disabled={page===pages.length-1} aria-label="Next page"><ArrowRight/></button></div></div></div></div>}
    {deliv===1&&<div className={siteMobile?'site-frame mobile':'site-frame'}><div className="site-chrome"><i/><i/><i/><span>{c.site.domain}</span><button className="site-toggle" onClick={()=>setSiteMobile(!siteMobile)} aria-label={siteMobile?'Switch to desktop preview':'Switch to mobile preview'} title={siteMobile?'Desktop preview':'Mobile preview'}>{siteMobile?<Monitor/>:<Smartphone/>}</button></div><div className="site-body" key={c.name}><div className="mini-nav"><b>{c.name}</b><div>{c.site.nav.map(n=><span key={n}>{n}</span>)}</div></div><div className="mini-hero"><div><p className="kicker">{c.site.kicker}</p><h3>{c.site.h}</h3><p>{c.site.p}</p><span className="mini-btn">See the work</span></div><figure><img src={`/images/${c.portrait}.webp`} alt="Sample website hero image for the fictional client" loading="lazy"/></figure></div><div className="mini-projects">{c.site.projects.map(([n,img])=><div key={n}><img src={`/images/${img}.webp`} alt={`${n} \u2014 fictional sample project`} loading="lazy"/><strong>{n}</strong></div>)}</div><div className="mini-about"><figure><img src={`/images/${c.site.aboutImg}.webp`} alt="About-page portrait of the fictional client" loading="lazy"/></figure><div><p className="kicker">About</p><h3>{c.site.aboutH}</h3><p>{c.site.aboutP}</p></div></div><div className="mini-journal"><p className="kicker">Journal</p>{c.site.journal.map(([d,t])=><div key={t}><span>{d}</span><strong>{t}</strong></div>)}</div><div className="mini-footer"><b>{c.name}</b><span>{c.site.foot}</span></div></div></div>}
    {deliv===2&&<div className="sheet">{c.sheet.map(([img,cap])=><figure key={img}><div className="ph"><img src={`/images/${img}.webp`} alt={`${cap} \u2014 sample headshot of the fictional client`} loading="lazy"/></div><figcaption>{cap}</figcaption></figure>)}</div>}
    {deliv===3&&<div className="film-wrap" key={c.film}><Video name={c.film}/></div>}
    <Reveal className="book-foot"><small>{delivCaps[deliv]}</small><a className="text-btn dark-text" href="#packages">Start yours <ArrowRight/></a></Reveal></section>
    <section id="packages" className="packages"><Reveal className="section-head"><p className="kicker">Ways to work together</p><h2><Words text={'Start with clarity.\nScale with confidence.'}/></h2><p>Choose a direction, then reserve your project with a $500 retainer. Final scope and pricing are confirmed in your written proposal.</p></Reveal><div className="package-grid">{packages.map(p=><Reveal className={p.featured?'package featured':'package'} key={p.name}>{p.featured&&<em>Most complete</em>}<p className="kicker">{p.label}</p><h3>{p.name}</h3><strong>{p.price}</strong><ul>{p.items.map(i=><li key={i}><Check/>{i}</li>)}</ul><button className={p.featured?'btn light':'btn dark'} onClick={()=>setCheckout(p.name)}>Choose {p.name}<ArrowRight/></button></Reveal>)}</div></section>
    <section id="about" className="about"><Reveal><p className="kicker">Lilikoi</p><h2><Words text={'Design direction for people becoming brands.'}/></h2></Reveal><Reveal><p>Lilikoi is Experience Plus’s personal branding studio. We combine brand strategy, editorial direction, image making, video, and AI-assisted production—without outsourcing judgment.</p></Reveal></section>
    <section className="closing"><Reveal><p className="kicker">Ready when you are</p><h2><Words text={'Make your name\nlook like a brand.'}/></h2><div className="actions"><a className="btn dark" href="#packages">View packages <ArrowRight/></a><a className="text-btn dark-text" href={CALL_URL} target="_blank" rel="noreferrer">Book a discovery call</a></div></Reveal></section>
  </main><footer><div className="footer-top"><a className="logo" href="#top"><Logo/></a><div className="footer-nav">{navLinks.map(([l,h])=><a href={h} key={l}>{l}</a>)}</div></div><p className="footer-note">Package prices are starting points; final scope and pricing are confirmed in a written proposal after a discovery call. Retainer payments are securely processed by Stripe. Portfolio imagery includes AI-assisted concept work created under human creative direction.</p><div className="legal-row"><span>© 2026 Ryan Hanau, Inc. All rights reserved. Lilikoi is a brand of Ryan Hanau, Inc.</span><div className="legal-links"><a href="https://www.experienceplus.ai/privacy-policy" target="_blank" rel="noreferrer">Privacy Policy</a><a href="https://www.experienceplus.ai/terms-and-conditions" target="_blank" rel="noreferrer">Terms & Conditions</a></div></div></footer>{checkout&&<Checkout choice={checkout} onClose={()=>setCheckout(null)}/>}</MotionConfig>}
