import { Fragment, useEffect, useState, type ReactNode } from 'react';
import { motion, MotionConfig, type Transition } from 'framer-motion';
import { ArrowRight, ChevronDown, Menu, X } from 'lucide-react';

const gravityBounce: Transition = { type: 'spring', stiffness: 110, damping: 11, mass: 1 };

const BOOK_URL='https://www.experienceplus.ai/book';
const navLinks:[string,string][]=[['Services','#services'],['Deliverable','#deliverable'],['Process','#process'],['Packages','#packages'],['About','#about']];
const services=[['01','Position','Audience, promise, proof, and voice—decided before anything is drawn. The argument your sales team can actually repeat.'],['02','Identify','Wordmark, color, type, and image direction built around your position—not borrowed from this year’s landing pages.'],['03','Systematize','Design tokens, component libraries, templates, and guidelines—so the brand survives contact with every team that uses it.'],['04','Launch','Website, sales collateral, pitch materials, and the launch plan—shipped, not handed over as a PDF.']];
const audiences=['B2B SaaS','Professional services','Funded startups','Rebrands & renames','Post-merger identities','Internal ventures'];
const packages=[
  {name:'Position',label:'Find your position',price:'From $7,500',items:['Positioning workshop','Messaging platform','Voice and naming direction','Competitive landscape','Creative brief for what’s next']},
  {name:'Identity',label:'Build the full system',price:'From $24,000',featured:true,items:['Everything in Position','Full visual identity','Design tokens + component library','Website hero system','Sales and pitch templates','Guidelines, shipped live']},
  {name:'Partner',label:'Stay coherent',price:'Custom quarterly',items:['Quarterly creative direction','Campaign and launch support','New surfaces, same system','Design system stewardship','Performance review']},
];
const deliverables=['Brand strategy and messaging platform','Identity: mark, color, type, imagery','Design tokens and component library','Sales, pitch, and campaign templates','Guidelines your teams actually read'];

function Mark(){return <svg className="mark" viewBox="0 0 32 32" aria-hidden="true"><rect x="2" y="2" width="28" height="28" fill="none" stroke="currentColor" strokeWidth="1.6"/><rect x="9" y="9" width="14" height="14" fill="var(--accent)"/></svg>}
function Logo(){return <><Mark/><span className="lt"><span>Brand</span><small>By Experience Plus · B2B studio</small></span></>}
function Reveal({children,className=''}:{children:ReactNode;className?:string}){return <motion.div className={`reveal ${className}`} initial={{y:-44,opacity:0}} whileInView={{y:0,opacity:1}} viewport={{once:true,amount:0.15}} transition={gravityBounce}>{children}</motion.div>}
function Words({text}:{text:string}){let i=0;return <>{text.split('\n').map((line,li)=><Fragment key={li}>{li>0&&<br/>}{line.split(' ').map((w,wi)=><Fragment key={wi}>{wi>0&&' '}<motion.span style={{display:'inline-block',willChange:'transform'}} initial={{y:'-0.8em',opacity:0}} whileInView={{y:0,opacity:1}} viewport={{once:true,amount:0.5}} transition={{...gravityBounce,delay:i++*0.07}}>{w}</motion.span></Fragment>)}</Fragment>)}</>}

export default function App(){const [menu,setMenu]=useState(false);const [scrolled,setScrolled]=useState(false);
  useEffect(()=>{const f=()=>setScrolled(window.scrollY>24);f();addEventListener('scroll',f,{passive:true});return()=>removeEventListener('scroll',f)},[]);
  return <MotionConfig reducedMotion="user">
  <header className={scrolled||menu?'scrolled':''}><a className="logo" href="#top"><Logo/></a><nav className={menu?'open':''}>{navLinks.map(([l,h])=><a href={h} onClick={()=>setMenu(false)} key={l}>{l}</a>)}<a className="nav-cta" href={BOOK_URL} target="_blank" rel="noreferrer">Book a discovery call</a></nav><button className="menu" onClick={()=>setMenu(!menu)} aria-label="Toggle menu">{menu?<X/>:<Menu/>}</button></header>
  <main id="top">
    <section className="hero"><img className="hero-img" src="/images/hero-workshop.webp" alt="A brand strategy workshop: printed identity boards reviewed on a long table" fetchPriority="high"/><div className="hero-shade"/><Reveal className="hero-copy"><p className="kicker light">Strategy · Identity · Design systems</p><h1><Words text={'Make the company\nlook like the work.'}/></h1><p>Brand strategy, identity, and design systems for B2B companies—one coherent system from pitch deck to product, built with human direction and AI-accelerated production.</p><div className="actions"><a className="btn light" href="#packages">See the packages <ArrowRight/></a><a className="text-btn" href="#services">What we do <ChevronDown/></a></div></Reveal></section>
    <section className="intro"><Reveal><p className="kicker">The proposition</p><h2><Words text={'Buyers research you before they ever reply.'}/></h2></Reveal><Reveal className="intro-copy"><p>Your company already has a reputation—in inboxes, on procurement shortlists, in the tabs your buyers open before a first call. We turn it into a deliberate system: a position worth repeating, an identity that carries it, and the design system that keeps every surface saying the same thing.</p><div className="audience-list">{audiences.map(x=><span key={x}>{x}</span>)}</div></Reveal></section>
    <section id="services" className="services"><Reveal className="section-head"><p className="kicker">One coherent identity</p><h2><Words text={'Strategy before design.\nA system before assets.'}/></h2></Reveal><div className="service-grid">{services.map(([n,t,d])=><Reveal key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></Reveal>)}</div></section>
    <section id="deliverable" className="split-film"><div className="video-wrap"><img src="/images/identity-detail.webp" alt="Corporate identity system detail: embossed marks and printed cards" loading="lazy"/></div><Reveal><p className="kicker">The deliverable</p><h2><Words text={'Systems, not just artwork.'}/></h2><p>Every engagement ends in working material—the identity applied, the templates live, the rules written down. AI accelerates the production; every decision still passes through a human point of view.</p><ul>{deliverables.map(x=><li key={x}>{x}</li>)}</ul></Reveal></section>
    <section id="process" className="process"><Reveal><p className="kicker light">The process</p><h2><Words text={'From position\nto every surface.'}/></h2></Reveal><div className="process-line">{['Discover','Position','Design','Systematize','Launch','Evolve'].map((x,i)=><Reveal key={x}><b>{String(i+1).padStart(2,'0')}</b><span>{x}</span></Reveal>)}</div></section>
    <section className="gallery"><Reveal className="section-head"><p className="kicker">The working method</p><h2><Words text={'Decided at the table.\nShipped as a system.'}/></h2></Reveal><div className="gallery-grid"><Reveal><figure><img src="/images/strategy-room.webp" alt="A strategy review at a standing table in a glass-walled room" loading="lazy"/><figcaption><span>Position</span><strong>Decisions before design</strong></figcaption></figure></Reveal><Reveal><figure><img src="/images/system-grid.webp" alt="A wall of pinned brand system boards: grids, color chips, spacing diagrams" loading="lazy"/><figcaption><span>System</span><strong>Rules that scale</strong></figcaption></figure></Reveal></div></section>
    <section id="packages" className="packages"><Reveal className="section-head"><p className="kicker">Ways to work together</p><h2><Words text={'Start with position.\nScale with a system.'}/></h2><p>Every engagement starts with a discovery call and a written proposal—scope and pricing confirmed before work begins.</p></Reveal><div className="package-grid">{packages.map(p=><Reveal className={p.featured?'package featured':'package'} key={p.name}>{p.featured&&<em>Most complete</em>}<p className="kicker">{p.label}</p><h3>{p.name}</h3><strong>{p.price}</strong><ul>{p.items.map(i=><li key={i}>{i}</li>)}</ul><a className={p.featured?'btn light':'btn dark'} href={BOOK_URL} target="_blank" rel="noreferrer">Book a discovery call <ArrowRight/></a></Reveal>)}</div></section>
    <section id="about" className="about"><Reveal><p className="kicker">Experience Plus</p><h2><Words text={'The studio behind the system.'}/></h2></Reveal><Reveal><p>Brand is Experience Plus’s B2B brand studio: strategy, identity, and design systems under one direction. For founders and executives building a <i>personal</i> brand, our sibling studio <a href="https://lilikoi.one" target="_blank" rel="noreferrer">Lilikoi</a> does for people what we do for companies.</p></Reveal></section>
    <section className="closing"><Reveal><p className="kicker">Ready when you are</p><h2><Words text={'Make your company\nlook inevitable.'}/></h2><div className="actions"><a className="btn dark" href={BOOK_URL} target="_blank" rel="noreferrer">Book a discovery call <ArrowRight/></a><a className="text-btn dark-text" href="#packages">View packages</a></div></Reveal></section>
  </main><footer><div className="footer-top"><a className="logo" href="#top"><Logo/></a><div className="footer-nav">{navLinks.map(([l,h])=><a href={h} key={l}>{l}</a>)}<a href="https://lilikoi.one" target="_blank" rel="noreferrer">Lilikoi</a></div></div><p className="footer-note">Package prices are starting points; final scope and pricing are confirmed in a written proposal after a discovery call. Imagery includes AI-assisted concept work created under human creative direction.</p><div className="legal-row"><span>© 2026 Experience Plus. All rights reserved.</span><div className="legal-links"><a href="https://experienceplus.ai/privacy-policy" target="_blank" rel="noreferrer">Privacy Policy</a><a href="https://experienceplus.ai/terms-and-conditions" target="_blank" rel="noreferrer">Terms & Conditions</a></div></div></footer></MotionConfig>}
