import { Fragment, useEffect, useState, type ReactNode } from 'react';
import { motion, MotionConfig, type Transition } from 'framer-motion';
import { ArrowRight, Check, ChevronDown, Menu, Pause, Play, X } from 'lucide-react';

const gravityBounce: Transition = { type: 'spring', stiffness: 110, damping: 11, mass: 1 };

const CALL_URL='https://meet.ryanh.com/';
const RETAINER_URL='https://buy.stripe.com/5kQaEZfeh0tqf3k7Q4bo400';
const navLinks:[string,string][]=[['Work','#work'],['Services','#services'],['Process','#process'],['Packages','#packages'],['About','#about']];
const packages=[
  {name:'Foundation',label:'Find your position',price:'From $2,400',items:['Positioning workshop','Messaging foundation','Visual direction','Profile image set','LinkedIn + biography refresh']},
  {name:'Signature',label:'Build the full system',price:'From $6,800',featured:true,items:['Everything in Foundation','Editorial photo direction','Personal brand film','30-day social launch library','Website hero system']},
  {name:'Ongoing',label:'Stay recognizable',price:'Custom monthly',items:['Quarterly creative direction','Monthly image + video production','Campaign concepts','Social content system','Performance review']},
];
const services=[['01','Position','A clear point of view, audience, promise, and voice before a camera turns on.'],['02','Direct','A visual world built around your presence—not borrowed from somebody else’s feed.'],['03','Produce','Portraits, brand films, vertical video, and campaign assets from one direction.'],['04','Launch','A reusable system for LinkedIn, Instagram, press, speaking, and your own site.']];
const audiences=['Founders & executives','Consultants & advisors','Creators & speakers','Independent professionals','Hospitality & wellness','Career reinvention'];

function Reveal({children,className=''}:{children:ReactNode;className?:string}){return <motion.div className={`reveal ${className}`} initial={{y:-44,opacity:0}} whileInView={{y:0,opacity:1}} viewport={{once:true,amount:0.15}} transition={gravityBounce}>{children}</motion.div>}
function Words({text}:{text:string}){let i=0;return <>{text.split('\n').map((line,li)=><Fragment key={li}>{li>0&&<br/>}{line.split(' ').map((w,wi)=><Fragment key={wi}>{wi>0&&' '}<motion.span style={{display:'inline-block',willChange:'transform'}} initial={{y:'-0.8em',opacity:0}} whileInView={{y:0,opacity:1}} viewport={{once:true,amount:0.5}} transition={{...gravityBounce,delay:i++*0.07}}>{w}</motion.span></Fragment>)}</Fragment>)}</>}
function Video({name,className='',loop=true}:{name:string;className?:string;loop?:boolean}){const [paused,setPaused]=useState(false);return <div className={`video-wrap ${className}`}><video autoPlay={!paused} muted loop={loop} playsInline preload="metadata" poster={`/images/${name}.webp`} ref={el=>{if(el)paused?el.pause():!el.ended&&el.play().catch(()=>{})}}><source src={`/media/${name}.mp4`} type="video/mp4"/></video><button className="video-control" onClick={()=>setPaused(!paused)} aria-label={paused?'Play background video':'Pause background video'}>{paused?<Play/>:<Pause/>}</button></div>}
function HeroCycle({names}:{names:string[]}){const [idx,setIdx]=useState(0);const [paused,setPaused]=useState(false);return <div className="video-wrap">{names.map((n,i)=>{const active=i===idx;const nxt=i===(idx+1)%names.length;return <video key={n} className={active?'hero-clip on':'hero-clip'} muted playsInline preload={active||nxt?'auto':'none'} poster={`/images/${n}.webp`} ref={el=>{if(!el)return;if(active&&!paused){el.play().catch(()=>{})}else{el.pause();if(!active)el.currentTime=0}}} onEnded={()=>{if(active)setIdx((idx+1)%names.length)}}><source src={`/media/${n}.mp4`} type="video/mp4"/></video>})}<button className="video-control" onClick={()=>setPaused(!paused)} aria-label={paused?'Play background video':'Pause background video'}>{paused?<Play/>:<Pause/>}</button></div>}
function Still({name,alt}:{name:string;alt:string}){return <div className="video-wrap"><img src={`/images/${name}.webp`} alt={alt} loading="lazy"/></div>}
function Checkout({choice,onClose}:{choice:string;onClose:()=>void}){useEffect(()=>{document.body.style.overflow='hidden';const k=(e:KeyboardEvent)=>e.key==='Escape'&&onClose();addEventListener('keydown',k);return()=>{document.body.style.overflow='';removeEventListener('keydown',k)}},[onClose]);return <div className="modal-bg" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="checkout" role="dialog" aria-modal="true" aria-labelledby="checkout-title"><button className="modal-x" onClick={onClose} aria-label="Close"><X/></button><p className="kicker">Secure retainer</p><h2 id="checkout-title">{choice}</h2><p>Reserve your project with a $500 retainer. Final scope, schedule, and total pricing are confirmed separately in a written proposal.</p><div className="stripe-stub"><span>Stripe Checkout</span><strong>$500 project retainer</strong><small>Secure payment opens in a new tab.</small></div><a className="btn dark" href={RETAINER_URL} target="_blank" rel="noreferrer">Pay $500 retainer <ArrowRight/></a><small>Payment is securely processed by Stripe.</small></div></div>}

export default function App(){const [menu,setMenu]=useState(false);const [checkout,setCheckout]=useState<string|null>(null);;return <MotionConfig reducedMotion="user">
  <header><a className="logo" href="#top"><span>Lilikoi</span><small>Personal branding studio</small></a><nav className={menu?'open':''}>{navLinks.map(([l,h])=><a href={h} onClick={()=>setMenu(false)} key={l}>{l}</a>)}<a className="nav-cta" href="#packages">Build your brand</a></nav><button className="menu" onClick={()=>setMenu(!menu)} aria-label="Toggle menu">{menu?<X/>:<Menu/>}</button></header>
  <main id="top">
    <section className="hero"><HeroCycle names={['hero-solo','hero-3','hero-4','hero-5','hero-2']}/><div className="hero-shade"/><Reveal className="hero-copy"><p className="kicker light">Strategy · Photography · Video · Content</p><h1><Words text={'A personal brand\npeople remember.'}/></h1><p>One recognizable system for how you look, sound, and show up—built with human direction and AI-accelerated production.</p><div className="actions"><a className="btn light" href="#packages">Build your brand <ArrowRight/></a><a className="text-btn" href="#work">See the work <ChevronDown/></a></div></Reveal></section>
    <section className="intro"><Reveal><p className="kicker">The proposition</p><h2><Words text={'Your brand should look as credible as the work behind it.'}/></h2></Reveal><Reveal className="intro-copy"><p>You already have a reputation. We turn it into a deliberate visual and verbal system—so the person people meet online matches the authority you bring into the room.</p><div className="audience-list">{audiences.map(x=><span key={x}>{x}</span>)}</div></Reveal></section>
    <section id="work" className="film-chapter"><Video name="founder-solo-2"/><div className="film-overlay"/><Reveal><p className="kicker light">Founder presence</p><h2><Words text={'Be visible.\nStay yourself.'}/></h2><p>Editorial imagery with enough polish to travel—and enough humanity to be believed.</p></Reveal></section>
    <section id="services" className="services"><Reveal className="section-head"><p className="kicker">One coherent identity</p><h2><Words text={'Strategy before content.\nA system before a feed.'}/></h2></Reveal><div className="service-grid">{services.map(([n,t,d])=><Reveal key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></Reveal>)}</div></section>
    <section className="portrait-work"><Reveal className="section-head"><p className="kicker">Selected directions</p><h2><Words text={'One person.\nA world built around them.'}/></h2></Reveal><div className="portrait-grid"><figure><img src="/images/portrait-architect.webp" alt="Editorial personal brand portrait of an architect in a Nordic studio" loading="lazy"/><figcaption><span>Architecture</span><strong>Quiet authority</strong></figcaption></figure><figure><img src="/images/portrait-founder.webp" alt="Editorial personal brand portrait of a technology founder in a gallery" loading="lazy"/><figcaption><span>Technology</span><strong>Visible leadership</strong></figcaption></figure><figure><img src="/images/portrait-chef.webp" alt="Editorial personal brand portrait of a chef founder" loading="lazy"/><figcaption><span>Hospitality</span><strong>Craft as identity</strong></figcaption></figure></div></section>
    <section className="split-film"><Still name="cd-still" alt="Creative director reviewing editorial photography in a studio"/><Reveal><p className="kicker">Creative direction</p><h2><Words text={'AI makes production faster. Taste makes it yours.'}/></h2><p>We use AI to expand the shot list, explore campaigns, and multiply formats. Every choice still passes through a human point of view.</p><ul><li><Check/>Environmental and studio portraits</li><li><Check/>Short-form and campaign video</li><li><Check/>Typography-led social assets</li><li><Check/>Website, press, and speaker kits</li></ul></Reveal></section>
    <section id="process" className="process"><Reveal><p className="kicker light">The process</p><h2><Words text={'From point of view\nto public presence.'}/></h2></Reveal><div className="process-line">{['Discover','Position','Direct','Produce','Launch','Evolve'].map((x,i)=><Reveal key={x}><b>{String(i+1).padStart(2,'0')}</b><span>{x}</span></Reveal>)}</div></section>
    <section className="film-chapter strategy"><Video name="strategy-film-v2"/><div className="film-overlay"/><Reveal><p className="kicker light">Built together</p><h2><Words text={'Your expertise.\nOur direction.'}/></h2><p>The work begins at a table, not inside a generator.</p></Reveal></section>
    <section id="packages" className="packages"><Reveal className="section-head"><p className="kicker">Ways to work together</p><h2><Words text={'Start with clarity.\nScale with confidence.'}/></h2><p>Choose a direction, then reserve your project with a $500 retainer. Final scope and pricing are confirmed in your written proposal.</p></Reveal><div className="package-grid">{packages.map(p=><Reveal className={p.featured?'package featured':'package'} key={p.name}>{p.featured&&<em>Most complete</em>}<p className="kicker">{p.label}</p><h3>{p.name}</h3><strong>{p.price}</strong><ul>{p.items.map(i=><li key={i}><Check/>{i}</li>)}</ul><button className={p.featured?'btn light':'btn dark'} onClick={()=>setCheckout(p.name)}>Choose {p.name}<ArrowRight/></button></Reveal>)}</div></section>
    <section id="about" className="about"><Reveal><p className="kicker">Lilikoi</p><h2><Words text={'Design direction for people becoming brands.'}/></h2></Reveal><Reveal><p>Lilikoi is Experience Plus’s personal branding studio. We combine brand strategy, editorial direction, image making, video, and AI-assisted production—without outsourcing judgment.</p></Reveal></section>
    <section className="closing"><Reveal><p className="kicker">Ready when you are</p><h2><Words text={'Make your name\nlook like a brand.'}/></h2><div className="actions"><a className="btn dark" href="#packages">View packages <ArrowRight/></a><a className="text-btn dark-text" href={CALL_URL} target="_blank" rel="noreferrer">Book a discovery call</a></div></Reveal></section>
  </main><footer><div className="footer-top"><a className="logo" href="#top"><span>Lilikoi</span><small>Personal branding studio</small></a><div className="footer-nav">{navLinks.map(([l,h])=><a href={h} key={l}>{l}</a>)}</div></div><p className="footer-note">Package prices are starting points; final scope and pricing are confirmed in a written proposal after a discovery call. Retainer payments are securely processed by Stripe. Portfolio imagery includes AI-assisted concept work created under human creative direction.</p><div className="legal-row"><span>© 2026 Lilikoi. All rights reserved.</span><div className="legal-links"><a href="https://www.ryanh.com/privacy-policy" target="_blank" rel="noreferrer">Privacy Policy</a><a href="https://www.ryanh.com/terms-and-conditions" target="_blank" rel="noreferrer">Terms & Conditions</a></div></div></footer>{checkout&&<Checkout choice={checkout} onClose={()=>setCheckout(null)}/>}</MotionConfig>}
